# Generated by Django 3.2.3 on 2021-06-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskListing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
