# Generated by Django 3.2.3 on 2021-06-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskListing', '0002_auto_20210603_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
